spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/stressdebugger}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

python:
  service:
    url: https://stressdebuggerai-production.up.railway.app
